---
# tasks file for teamix.admins
- name: Include Distro dependent vars
  include_vars: "{{ item }}"
  with_items:
    - "{{ ansible_os_family }}.yml"
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"

- name: Ensure ssh_allow group exists.
  group:
    name: "{{ tmxopenssh_allow_group }}"
    state: present
    system: true

- name: Fetch list of admin users
  shell: getent passwd | awk -F ":" '{ if ($3 >= 10000 && $3 < 20000 ) { print $1 }}'
  register: admin_users_system
  changed_when: false

- name: Delete admin users (against whitelist)
  user:
    groups: ""
    name: "{{ item }}"
    state: absent
  with_items: "{{ admin_users_system.stdout_lines }}"
  when: item not in tmxadmins_admin_users.keys()

- name: Archive home dirs of removed admins
  archive:
    dest: /home/{{ ansible_date_time.iso8601 }}_{{ item }}.tar.gz
    owner: root
    group: "{{ root_group }}"
    mode: 0600
    path: /home/{{ item }}
    remove: True
  with_items: "{{ admin_users_system.stdout_lines }}"
  when: item not in tmxadmins_admin_users.keys()

- name: Create admin users.
  user:
    append: "yes"
    groups:
      - "{{ tmxsudo_nopasswd_group }}"
      - "{{ tmxopenssh_allow_group }}"
    name: "{{ item.key }}"
    uid: "{{ item.value.uid }}"
    shell: "{{ tmxadmins_shell }}"
    comment: "Admin - {{ item.value.fullname }}"
    password: "!!"
    state: present
    update_password: always
  with_dict: "{{ tmxadmins_admin_users }}"
  loop_control:
    label: "{{ item.key }}"

- name: Install SSH keys for admin users.
  authorized_key:
    user: "{{ item.key }}"
    exclusive: "yes"
    key: "{{ item.value.sshkey }}"
    manage_dir: "yes"
    state: present
  with_dict: "{{ tmxadmins_admin_users }}"
  loop_control:
    label: "{{ item.key }}"

- name: Ensure root is in ssh_allow.
  user: append=yes groups=ssh_allow name=root

- name: Install ansible SSH key for root user
  authorized_key:
    key: "{{ tmxadmins_root_pubkey }}"
    manage_dir: "yes"
    state: present
    user: root
    exclusive: True
