---
# tasks file for teamix.admins
- name: Create sudonopw group.
  group: name=sudonopw  state=present system=yes

- name: Create ssh_allow group.
  group: name=ssh_allow state=present system=true

- name: Generate sudo config (sudoers.d file).
  template: dest=/etc/sudoers.d/ansible group=root mode=0440 owner=root src=sudoers_sudonopw.j2  validate="visudo -q -c -f %s"

- name: Generate sudo config (include sudoers.d).
  lineinfile: dest=/etc/sudoers group=root mode=0440 owner=root insertafter=EOF regexp='^#includedir /etc/sudoers.d' state=present validate="visudo -q -c -f %s" line='#includedir /etc/sudoers.d'

- name: Create admin users.
  user:
    append: "yes"
    # Ansible does not support an array here currently -> starts in V2.3
    groups: sudonopw,ssh_allow
    name: "{{ item.key }}"
    uid: "{{ item.value.uid }}"
    shell: /bin/bash
    comment: "Admin - {{ item.value.fullname }}"
    password: "!!"
    state: present
    update_password: always
  with_dict: "{{ admin_users }}"

- name: Install SSH keys for admin users.
  authorized_key:
    user: "{{ item.key }}"
    exclusive: "yes"
    key: "{{ item.value.sshkey }}"
    manage_dir: "yes"
    state: present
  with_dict: "{{ admin_users }}"

- name: Purge old admins.
  user: force=yes name={{ item.key }} state=absent groups=''
  with_dict: "{{ purge_admins }}"

- name: Ensure root is in ssh_allow.
  user: append=yes groups=ssh_allow name=root

- name: Install admin SSH keys for root user.
  authorized_key:
    key: "{{ item.value.sshkey }}"
    manage_dir: "yes"
    state: present
    user: root
  with_dict: "{{ admin_users }}"

- name: purge old admin SSH keys for root user.
  authorized_key:
    key: "{{ item.value.sshkey }}"
    manage_dir: "yes"
    state: absent
    user: root
  when: "item.value.sshkey is defined"
  with_dict: "{{ purge_admins }}"
